CREATE TABLE `product` (
  `PRO_ID` INT NOT NULL,
  `PRO_NAME` VARCHAR(20) NOT NULL DEFAULT 'DUMMY',
  `PRO_DESC` VARCHAR(60) NULL,
  `CAT_ID` INT NOT NULL,
  PRIMARY KEY (`PRO_ID`),
  INDEX `CAT_ID_idx` (`CAT_ID` ASC) VISIBLE,
  CONSTRAINT `CAT_ID`
    FOREIGN KEY (`CAT_ID`)
    REFERENCES `category` (`CAT_ID`));
CREATE TABLE `E-COMMERCE`.`supplier_pricing` (
  `PRICING_ID` INT NOT NULL,
  `PRO_ID` INT NOT NULL,
  `SUPP_ID` INT NOT NULL,
  `SUPP_PRICE` INT NULL DEFAULT 0,
  PRIMARY KEY (`PRICING_ID`),
  INDEX `SUPP_ID_idx` (`SUPP_ID` ASC, `PRO_ID` ASC) VISIBLE,
  CONSTRAINT `PRO_ID`
    FOREIGN KEY (`PRO_ID`)
    REFERENCES `E-COMMERCE`.`product` (`PRO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SUPP_ID`
    FOREIGN KEY (`SUPP_ID`)
    REFERENCES `E-COMMERCE`.`supplier` (`SUPP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    CREATE TABLE `E-COMMERCE`.`order` (
  `ORD_ID` INT NOT NULL,
  `ORD_AMOUNT` INT NOT NULL,
  `ORD_DATE` INT NOT NULL,
  `CUS_ID` INT NOT NULL,
  `PRICING_ID` INT NOT NULL,
  PRIMARY KEY (`ORD_ID`),
  INDEX `CUS_ID_idx` (`CUS_ID` ASC, `PRICING_ID` ASC) VISIBLE,
  CONSTRAINT `CUS_ID`
    FOREIGN KEY (`CUS_ID`)
    REFERENCES `E-COMMERCE`.`customer` (`CUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRICING_ID`
    FOREIGN KEY (`PRICING_ID`)
    REFERENCES `E-COMMERCE`.`supplier_pricing` (`PRICING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    

